apiVersion: v1
kind: Service
metadata:
  name: dynamic-config-poc
spec:
  selector:
    app: dynamic-config-poc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
